export default {
    "ABeeZee": "https://fonts.googleapis.com/css2?family=ABeeZee&display=swap",
    "Abel": "https://fonts.googleapis.com/css2?family=Abel&display=swap",
    "Abhaya Libre": "https://fonts.googleapis.com/css2?family=Abhaya+Libre&display=swap",
    "Abril Fatface": "https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap",
    "Aclonica": "https://fonts.googleapis.com/css2?family=Aclonica&display=swap",
    "Acme": "https://fonts.googleapis.com/css2?family=Acme&display=swap",
    "Actor": "https://fonts.googleapis.com/css2?family=Actor&display=swap",
    "Adamina": "https://fonts.googleapis.com/css2?family=Adamina&display=swap",
    "Advent Pro": "https://fonts.googleapis.com/css2?family=Advent+Pro&display=swap",
    "Aguafina Script": "https://fonts.googleapis.com/css2?family=Aguafina+Script&display=swap",
    "Akronim": "https://fonts.googleapis.com/css2?family=Akronim&display=swap",
    "Aladin": "https://fonts.googleapis.com/css2?family=Aladin&display=swap",
    "Aldrich": "https://fonts.googleapis.com/css2?family=Aldrich&display=swap",
    "Alef": "https://fonts.googleapis.com/css2?family=Alef&display=swap",
    "Alegreya": "https://fonts.googleapis.com/css2?family=Alegreya&display=swap",
    "Alegreya SC": "https://fonts.googleapis.com/css2?family=Alegreya+SC&display=swap",
    "Alegreya Sans": "https://fonts.googleapis.com/css2?family=Alegreya+Sans&display=swap",
    "Alegreya Sans SC": "https://fonts.googleapis.com/css2?family=Alegreya+Sans+SC&display=swap",
    "Aleo": "https://fonts.googleapis.com/css2?family=Aleo&display=swap",
    "Alex Brush": "https://fonts.googleapis.com/css2?family=Alex+Brush&display=swap",
    "Alfa Slab One": "https://fonts.googleapis.com/css2?family=Alfa+Slab+One&display=swap",
    "Alice": "https://fonts.googleapis.com/css2?family=Alice&display=swap",
    "Alike": "https://fonts.googleapis.com/css2?family=Alike&display=swap",
    "Alike Angular": "https://fonts.googleapis.com/css2?family=Alike+Angular&display=swap",
    "Allan": "https://fonts.googleapis.com/css2?family=Allan&display=swap",
    "Allerta": "https://fonts.googleapis.com/css2?family=Allerta&display=swap",
    "Allerta Stencil": "https://fonts.googleapis.com/css2?family=Allerta+Stencil&display=swap",
    "Allura": "https://fonts.googleapis.com/css2?family=Allura&display=swap",
    "Almendra": "https://fonts.googleapis.com/css2?family=Almendra&display=swap",
    "Almendra Display": "https://fonts.googleapis.com/css2?family=Almendra+Display&display=swap",
    "Almendra SC": "https://fonts.googleapis.com/css2?family=Almendra+SC&display=swap",
    "Amarante": "https://fonts.googleapis.com/css2?family=Amarante&display=swap",
    "Amaranth": "https://fonts.googleapis.com/css2?family=Amaranth&display=swap",
    "Amatic SC": "https://fonts.googleapis.com/css2?family=Amatic+SC&display=swap",
    "Amethysta": "https://fonts.googleapis.com/css2?family=Amethysta&display=swap",
    "Amiko": "https://fonts.googleapis.com/css2?family=Amiko&display=swap",
    "Amiri": "https://fonts.googleapis.com/css2?family=Amiri&display=swap",
    "Amita": "https://fonts.googleapis.com/css2?family=Amita&display=swap",
    "Anaheim": "https://fonts.googleapis.com/css2?family=Anaheim&display=swap",
    "Andada": "https://fonts.googleapis.com/css2?family=Andada&display=swap",
    "Andika": "https://fonts.googleapis.com/css2?family=Andika&display=swap",
    "Angkor": "https://fonts.googleapis.com/css2?family=Angkor&display=swap",
    "Annie Use Your Telescope": "https://fonts.googleapis.com/css2?family=Annie+Use+Your+Telescope&display=swap",
    "Anonymous Pro": "https://fonts.googleapis.com/css2?family=Anonymous+Pro&display=swap",
    "Antic": "https://fonts.googleapis.com/css2?family=Antic&display=swap",
    "Antic Didone": "https://fonts.googleapis.com/css2?family=Antic+Didone&display=swap",
    "Antic Slab": "https://fonts.googleapis.com/css2?family=Antic+Slab&display=swap",
    "Anton": "https://fonts.googleapis.com/css2?family=Anton&display=swap",
    "Arapey": "https://fonts.googleapis.com/css2?family=Arapey&display=swap",
    "Arbutus": "https://fonts.googleapis.com/css2?family=Arbutus&display=swap",
    "Arbutus Slab": "https://fonts.googleapis.com/css2?family=Arbutus+Slab&display=swap",
    "Architects Daughter": "https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap",
    "Archivo": "https://fonts.googleapis.com/css2?family=Archivo&display=swap",
    "Archivo Black": "https://fonts.googleapis.com/css2?family=Archivo+Black&display=swap",
    "Archivo Narrow": "https://fonts.googleapis.com/css2?family=Archivo+Narrow&display=swap",
    "Aref Ruqaa": "https://fonts.googleapis.com/css2?family=Aref+Ruqaa&display=swap",
    "Arial": null,
    "Arial Black": null,
    "Arima Madurai": "https://fonts.googleapis.com/css2?family=Arima+Madurai&display=swap",
    "Arimo": "https://fonts.googleapis.com/css2?family=Arimo&display=swap",
    "Arizonia": "https://fonts.googleapis.com/css2?family=Arizonia&display=swap",
    "Armata": "https://fonts.googleapis.com/css2?family=Armata&display=swap",
    "Arsenal": "https://fonts.googleapis.com/css2?family=Arsenal&display=swap",
    "Artifika": "https://fonts.googleapis.com/css2?family=Artifika&display=swap",
    "Arvo": "https://fonts.googleapis.com/css2?family=Arvo&display=swap",
    "Arya": "https://fonts.googleapis.com/css2?family=Arya&display=swap",
    "Asap": "https://fonts.googleapis.com/css2?family=Asap&display=swap",
    "Asap Condensed": "https://fonts.googleapis.com/css2?family=Asap+Condensed&display=swap",
    "Asar": "https://fonts.googleapis.com/css2?family=Asar&display=swap",
    "Asset": "https://fonts.googleapis.com/css2?family=Asset&display=swap",
    "Assistant": "https://fonts.googleapis.com/css2?family=Assistant&display=swap",
    "Astloch": "https://fonts.googleapis.com/css2?family=Astloch&display=swap",
    "Asul": "https://fonts.googleapis.com/css2?family=Asul&display=swap",
    "Athiti": "https://fonts.googleapis.com/css2?family=Athiti&display=swap",
    "Atma": "https://fonts.googleapis.com/css2?family=Atma&display=swap",
    "Atomic Age": "https://fonts.googleapis.com/css2?family=Atomic+Age&display=swap",
    "Aubrey": "https://fonts.googleapis.com/css2?family=Aubrey&display=swap",
    "Audiowide": "https://fonts.googleapis.com/css2?family=Audiowide&display=swap",
    "Autour One": "https://fonts.googleapis.com/css2?family=Autour+One&display=swap",
    "Average": "https://fonts.googleapis.com/css2?family=Average&display=swap",
    "Average Sans": "https://fonts.googleapis.com/css2?family=Average+Sans&display=swap",
    "Averia Gruesa Libre": "https://fonts.googleapis.com/css2?family=Averia+Gruesa+Libre&display=swap",
    "Averia Libre": "https://fonts.googleapis.com/css2?family=Averia+Libre&display=swap",
    "Averia Sans Libre": "https://fonts.googleapis.com/css2?family=Averia+Sans+Libre&display=swap",
    "Averia Serif Libre": "https://fonts.googleapis.com/css2?family=Averia+Serif+Libre&display=swap",
    "B612": "https://fonts.googleapis.com/css2?family=B612&display=swap",
    "B612 Mono": "https://fonts.googleapis.com/css2?family=B612+Mono&display=swap",
    "Bad Script": "https://fonts.googleapis.com/css2?family=Bad+Script&display=swap",
    "Bahiana": "https://fonts.googleapis.com/css2?family=Bahiana&display=swap",
    "Bahianita": "https://fonts.googleapis.com/css2?family=Bahianita&display=swap",
    "Bai Jamjuree": "https://fonts.googleapis.com/css2?family=Bai+Jamjuree&display=swap",
    "Baloo": "https://fonts.googleapis.com/css2?family=Baloo&display=swap",
    "Baloo Bhai": "https://fonts.googleapis.com/css2?family=Baloo+Bhai&display=swap",
    "Baloo Bhaijaan": "https://fonts.googleapis.com/css2?family=Baloo+Bhaijaan&display=swap",
    "Baloo Bhaina": "https://fonts.googleapis.com/css2?family=Baloo+Bhaina&display=swap",
    "Baloo Chettan": "https://fonts.googleapis.com/css2?family=Baloo+Chettan&display=swap",
    "Baloo Da": "https://fonts.googleapis.com/css2?family=Baloo+Da&display=swap",
    "Baloo Paaji": "https://fonts.googleapis.com/css2?family=Baloo+Paaji&display=swap",
    "Baloo Tamma": "https://fonts.googleapis.com/css2?family=Baloo+Tamma&display=swap",
    "Baloo Tammudu": "https://fonts.googleapis.com/css2?family=Baloo+Tammudu&display=swap",
    "Baloo Thambi": "https://fonts.googleapis.com/css2?family=Baloo+Thambi&display=swap",
    "Balthazar": "https://fonts.googleapis.com/css2?family=Balthazar&display=swap",
    "Bangers": "https://fonts.googleapis.com/css2?family=Bangers&display=swap",
    "Barlow": "https://fonts.googleapis.com/css2?family=Barlow&display=swap",
    "Barlow Condensed": "https://fonts.googleapis.com/css2?family=Barlow+Condensed&display=swap",
    "Barlow Semi Condensed": "https://fonts.googleapis.com/css2?family=Barlow+Semi+Condensed&display=swap",
    "Barriecito": "https://fonts.googleapis.com/css2?family=Barriecito&display=swap",
    "Barrio": "https://fonts.googleapis.com/css2?family=Barrio&display=swap",
    "Basic": "https://fonts.googleapis.com/css2?family=Basic&display=swap",
    "Battambang": "https://fonts.googleapis.com/css2?family=Battambang&display=swap",
    "Baumans": "https://fonts.googleapis.com/css2?family=Baumans&display=swap",
    "Bayon": "https://fonts.googleapis.com/css2?family=Bayon&display=swap",
    "Belgrano": "https://fonts.googleapis.com/css2?family=Belgrano&display=swap",
    "Bellefair": "https://fonts.googleapis.com/css2?family=Bellefair&display=swap",
    "Belleza": "https://fonts.googleapis.com/css2?family=Belleza&display=swap",
    "BenchNine": "https://fonts.googleapis.com/css2?family=BenchNine&display=swap",
    "Bentham": "https://fonts.googleapis.com/css2?family=Bentham&display=swap",
    "Berkshire Swash": "https://fonts.googleapis.com/css2?family=Berkshire+Swash&display=swap",
    "Beth Ellen": "https://fonts.googleapis.com/css2?family=Beth+Ellen&display=swap",
    "Bevan": "https://fonts.googleapis.com/css2?family=Bevan&display=swap",
    "Bigelow Rules": "https://fonts.googleapis.com/css2?family=Bigelow+Rules&display=swap",
    "Bigshot One": "https://fonts.googleapis.com/css2?family=Bigshot+One&display=swap",
    "Bilbo": "https://fonts.googleapis.com/css2?family=Bilbo&display=swap",
    "Bilbo Swash Caps": "https://fonts.googleapis.com/css2?family=Bilbo+Swash+Caps&display=swap",
    "BioRhyme": "https://fonts.googleapis.com/css2?family=BioRhyme&display=swap",
    "BioRhyme Expanded": "https://fonts.googleapis.com/css2?family=BioRhyme+Expanded&display=swap",
    "Biryani": "https://fonts.googleapis.com/css2?family=Biryani&display=swap",
    "Bitter": "https://fonts.googleapis.com/css2?family=Bitter&display=swap",
    "Black And White Picture": "https://fonts.googleapis.com/css2?family=Black+And+White+Picture&display=swap",
    "Black Han Sans": "https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap",
    "Black Ops One": "https://fonts.googleapis.com/css2?family=Black+Ops+One&display=swap",
    "Blinker": "https://fonts.googleapis.com/css2?family=Blinker&display=swap",
    "Bokor": "https://fonts.googleapis.com/css2?family=Bokor&display=swap",
    "Bonbon": "https://fonts.googleapis.com/css2?family=Bonbon&display=swap",
    "Boogaloo": "https://fonts.googleapis.com/css2?family=Boogaloo&display=swap",
    "Bowlby One": "https://fonts.googleapis.com/css2?family=Bowlby+One&display=swap",
    "Bowlby One SC": "https://fonts.googleapis.com/css2?family=Bowlby+One+SC&display=swap",
    "Brawler": "https://fonts.googleapis.com/css2?family=Brawler&display=swap",
    "Bree Serif": "https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap",
    "Bubblegum Sans": "https://fonts.googleapis.com/css2?family=Bubblegum+Sans&display=swap",
    "Bubbler One": "https://fonts.googleapis.com/css2?family=Bubbler+One&display=swap",
    "Buda": "https://fonts.googleapis.com/css2?family=Buda&display=swap",
    "Buenard": "https://fonts.googleapis.com/css2?family=Buenard&display=swap",
    "Bungee": "https://fonts.googleapis.com/css2?family=Bungee&display=swap",
    "Bungee Hairline": "https://fonts.googleapis.com/css2?family=Bungee+Hairline&display=swap",
    "Bungee Inline": "https://fonts.googleapis.com/css2?family=Bungee+Inline&display=swap",
    "Bungee Outline": "https://fonts.googleapis.com/css2?family=Bungee+Outline&display=swap",
    "Bungee Shade": "https://fonts.googleapis.com/css2?family=Bungee+Shade&display=swap",
    "Butcherman": "https://fonts.googleapis.com/css2?family=Butcherman&display=swap",
    "Butterfly Kids": "https://fonts.googleapis.com/css2?family=Butterfly+Kids&display=swap",
    "Cabin": "https://fonts.googleapis.com/css2?family=Cabin&display=swap",
    "Cabin Condensed": "https://fonts.googleapis.com/css2?family=Cabin+Condensed&display=swap",
    "Cabin Sketch": "https://fonts.googleapis.com/css2?family=Cabin+Sketch&display=swap",
    "Caesar Dressing": "https://fonts.googleapis.com/css2?family=Caesar+Dressing&display=swap",
    "Cagliostro": "https://fonts.googleapis.com/css2?family=Cagliostro&display=swap",
    "Cairo": "https://fonts.googleapis.com/css2?family=Cairo&display=swap",
    "Calligraffitti": "https://fonts.googleapis.com/css2?family=Calligraffitti&display=swap",
    "Cambay": "https://fonts.googleapis.com/css2?family=Cambay&display=swap",
    "Cambo": "https://fonts.googleapis.com/css2?family=Cambo&display=swap",
    "Candal": "https://fonts.googleapis.com/css2?family=Candal&display=swap",
    "Cantarell": "https://fonts.googleapis.com/css2?family=Cantarell&display=swap",
    "Cantata One": "https://fonts.googleapis.com/css2?family=Cantata+One&display=swap",
    "Cantora One": "https://fonts.googleapis.com/css2?family=Cantora+One&display=swap",
    "Capriola": "https://fonts.googleapis.com/css2?family=Capriola&display=swap",
    "Cardo": "https://fonts.googleapis.com/css2?family=Cardo&display=swap",
    "Carme": "https://fonts.googleapis.com/css2?family=Carme&display=swap",
    "Carrois Gothic": "https://fonts.googleapis.com/css2?family=Carrois+Gothic&display=swap",
    "Carrois Gothic SC": "https://fonts.googleapis.com/css2?family=Carrois+Gothic+SC&display=swap",
    "Carter One": "https://fonts.googleapis.com/css2?family=Carter+One&display=swap",
    "Catamaran": "https://fonts.googleapis.com/css2?family=Catamaran&display=swap",
    "Caudex": "https://fonts.googleapis.com/css2?family=Caudex&display=swap",
    "Caveat": "https://fonts.googleapis.com/css2?family=Caveat&display=swap",
    "Caveat Brush": "https://fonts.googleapis.com/css2?family=Caveat+Brush&display=swap",
    "Cedarville Cursive": "https://fonts.googleapis.com/css2?family=Cedarville+Cursive&display=swap",
    "Ceviche One": "https://fonts.googleapis.com/css2?family=Ceviche+One&display=swap",
    "Chakra Petch": "https://fonts.googleapis.com/css2?family=Chakra+Petch&display=swap",
    "Changa": "https://fonts.googleapis.com/css2?family=Changa&display=swap",
    "Changa One": "https://fonts.googleapis.com/css2?family=Changa+One&display=swap",
    "Chango": "https://fonts.googleapis.com/css2?family=Chango&display=swap",
    "Charm": "https://fonts.googleapis.com/css2?family=Charm&display=swap",
    "Charmonman": "https://fonts.googleapis.com/css2?family=Charmonman&display=swap",
    "Chathura": "https://fonts.googleapis.com/css2?family=Chathura&display=swap",
    "Chau Philomene One": "https://fonts.googleapis.com/css2?family=Chau+Philomene+One&display=swap",
    "Chela One": "https://fonts.googleapis.com/css2?family=Chela+One&display=swap",
    "Chelsea Market": "https://fonts.googleapis.com/css2?family=Chelsea+Market&display=swap",
    "Chenla": "https://fonts.googleapis.com/css2?family=Chenla&display=swap",
    "Cherry Cream Soda": "https://fonts.googleapis.com/css2?family=Cherry+Cream+Soda&display=swap",
    "Cherry Swash": "https://fonts.googleapis.com/css2?family=Cherry+Swash&display=swap",
    "Chewy": "https://fonts.googleapis.com/css2?family=Chewy&display=swap",
    "Chicle": "https://fonts.googleapis.com/css2?family=Chicle&display=swap",
    "Chivo": "https://fonts.googleapis.com/css2?family=Chivo&display=swap",
    "Chonburi": "https://fonts.googleapis.com/css2?family=Chonburi&display=swap",
    "Cinzel": "https://fonts.googleapis.com/css2?family=Cinzel&display=swap",
    "Cinzel Decorative": "https://fonts.googleapis.com/css2?family=Cinzel+Decorative&display=swap",
    "Clicker Script": "https://fonts.googleapis.com/css2?family=Clicker+Script&display=swap",
    "Coda": "https://fonts.googleapis.com/css2?family=Coda&display=swap",
    "Coda Caption": "https://fonts.googleapis.com/css2?family=Coda+Caption&display=swap",
    "Codystar": "https://fonts.googleapis.com/css2?family=Codystar&display=swap",
    "Coiny": "https://fonts.googleapis.com/css2?family=Coiny&display=swap",
    "Combo": "https://fonts.googleapis.com/css2?family=Combo&display=swap",
    "Comfortaa": "https://fonts.googleapis.com/css2?family=Comfortaa&display=swap",
    "Comic Sans MS": null,
    "Coming Soon": "https://fonts.googleapis.com/css2?family=Coming+Soon&display=swap",
    "Concert One": "https://fonts.googleapis.com/css2?family=Concert+One&display=swap",
    "Condiment": "https://fonts.googleapis.com/css2?family=Condiment&display=swap",
    "Content": "https://fonts.googleapis.com/css2?family=Content&display=swap",
    "Contrail One": "https://fonts.googleapis.com/css2?family=Contrail+One&display=swap",
    "Convergence": "https://fonts.googleapis.com/css2?family=Convergence&display=swap",
    "Cookie": "https://fonts.googleapis.com/css2?family=Cookie&display=swap",
    "Copse": "https://fonts.googleapis.com/css2?family=Copse&display=swap",
    "Corben": "https://fonts.googleapis.com/css2?family=Corben&display=swap",
    "Cormorant": "https://fonts.googleapis.com/css2?family=Cormorant&display=swap",
    "Cormorant Garamond": "https://fonts.googleapis.com/css2?family=Cormorant+Garamond&display=swap",
    "Cormorant Infant": "https://fonts.googleapis.com/css2?family=Cormorant+Infant&display=swap",
    "Cormorant SC": "https://fonts.googleapis.com/css2?family=Cormorant+SC&display=swap",
    "Cormorant Unicase": "https://fonts.googleapis.com/css2?family=Cormorant+Unicase&display=swap",
    "Cormorant Upright": "https://fonts.googleapis.com/css2?family=Cormorant+Upright&display=swap",
    "Courgette": "https://fonts.googleapis.com/css2?family=Courgette&display=swap",
    "Courier New": null,
    "Cousine": "https://fonts.googleapis.com/css2?family=Cousine&display=swap",
    "Coustard": "https://fonts.googleapis.com/css2?family=Coustard&display=swap",
    "Covered By Your Grace": "https://fonts.googleapis.com/css2?family=Covered+By+Your+Grace&display=swap",
    "Crafty Girls": "https://fonts.googleapis.com/css2?family=Crafty+Girls&display=swap",
    "Creepster": "https://fonts.googleapis.com/css2?family=Creepster&display=swap",
    "Crete Round": "https://fonts.googleapis.com/css2?family=Crete+Round&display=swap",
    "Crimson Pro": "https://fonts.googleapis.com/css2?family=Crimson+Pro&display=swap",
    "Crimson Text": "https://fonts.googleapis.com/css2?family=Crimson+Text&display=swap",
    "Croissant One": "https://fonts.googleapis.com/css2?family=Croissant+One&display=swap",
    "Crushed": "https://fonts.googleapis.com/css2?family=Crushed&display=swap",
    "Cuprum": "https://fonts.googleapis.com/css2?family=Cuprum&display=swap",
    "Cute Font": "https://fonts.googleapis.com/css2?family=Cute+Font&display=swap",
    "Cutive": "https://fonts.googleapis.com/css2?family=Cutive&display=swap",
    "Cutive Mono": "https://fonts.googleapis.com/css2?family=Cutive+Mono&display=swap",
    "DM Sans": "https://fonts.googleapis.com/css2?family=DM+Sans&display=swap",
    "DM Serif Display": "https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap",
    "DM Serif Text": "https://fonts.googleapis.com/css2?family=DM+Serif+Text&display=swap",
    "Damion": "https://fonts.googleapis.com/css2?family=Damion&display=swap",
    "Dancing Script": "https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap",
    "Dangrek": "https://fonts.googleapis.com/css2?family=Dangrek&display=swap",
    "Darker Grotesque": "https://fonts.googleapis.com/css2?family=Darker+Grotesque&display=swap",
    "David Libre": "https://fonts.googleapis.com/css2?family=David+Libre&display=swap",
    "Dawning of a New Day": "https://fonts.googleapis.com/css2?family=Dawning+of+a+New+Day&display=swap",
    "Days One": "https://fonts.googleapis.com/css2?family=Days+One&display=swap",
    "Dekko": "https://fonts.googleapis.com/css2?family=Dekko&display=swap",
    "Delius": "https://fonts.googleapis.com/css2?family=Delius&display=swap",
    "Delius Swash Caps": "https://fonts.googleapis.com/css2?family=Delius+Swash+Caps&display=swap",
    "Delius Unicase": "https://fonts.googleapis.com/css2?family=Delius+Unicase&display=swap",
    "Della Respira": "https://fonts.googleapis.com/css2?family=Della+Respira&display=swap",
    "Denk One": "https://fonts.googleapis.com/css2?family=Denk+One&display=swap",
    "Devonshire": "https://fonts.googleapis.com/css2?family=Devonshire&display=swap",
    "Dhurjati": "https://fonts.googleapis.com/css2?family=Dhurjati&display=swap",
    "Didact Gothic": "https://fonts.googleapis.com/css2?family=Didact+Gothic&display=swap",
    "Diplomata": "https://fonts.googleapis.com/css2?family=Diplomata&display=swap",
    "Diplomata SC": "https://fonts.googleapis.com/css2?family=Diplomata+SC&display=swap",
    "Do Hyeon": "https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap",
    "Dokdo": "https://fonts.googleapis.com/css2?family=Dokdo&display=swap",
    "Domine": "https://fonts.googleapis.com/css2?family=Domine&display=swap",
    "Donegal One": "https://fonts.googleapis.com/css2?family=Donegal+One&display=swap",
    "Doppio One": "https://fonts.googleapis.com/css2?family=Doppio+One&display=swap",
    "Dorsa": "https://fonts.googleapis.com/css2?family=Dorsa&display=swap",
    "Dosis": "https://fonts.googleapis.com/css2?family=Dosis&display=swap",
    "Dr Sugiyama": "https://fonts.googleapis.com/css2?family=Dr+Sugiyama&display=swap",
    "Duru Sans": "https://fonts.googleapis.com/css2?family=Duru+Sans&display=swap",
    "Dynalight": "https://fonts.googleapis.com/css2?family=Dynalight&display=swap",
    "EB Garamond": "https://fonts.googleapis.com/css2?family=EB+Garamond&display=swap",
    "Eagle Lake": "https://fonts.googleapis.com/css2?family=Eagle+Lake&display=swap",
    "East Sea Dokdo": "https://fonts.googleapis.com/css2?family=East+Sea+Dokdo&display=swap",
    "Eater": "https://fonts.googleapis.com/css2?family=Eater&display=swap",
    "Economica": "https://fonts.googleapis.com/css2?family=Economica&display=swap",
    "Eczar": "https://fonts.googleapis.com/css2?family=Eczar&display=swap",
    "El Messiri": "https://fonts.googleapis.com/css2?family=El+Messiri&display=swap",
    "Electrolize": "https://fonts.googleapis.com/css2?family=Electrolize&display=swap",
    "Elsie": "https://fonts.googleapis.com/css2?family=Elsie&display=swap",
    "Elsie Swash Caps": "https://fonts.googleapis.com/css2?family=Elsie+Swash+Caps&display=swap",
    "Emblema One": "https://fonts.googleapis.com/css2?family=Emblema+One&display=swap",
    "Emilys Candy": "https://fonts.googleapis.com/css2?family=Emilys+Candy&display=swap",
    "Encode Sans": "https://fonts.googleapis.com/css2?family=Encode+Sans&display=swap",
    "Encode Sans Condensed": "https://fonts.googleapis.com/css2?family=Encode+Sans+Condensed&display=swap",
    "Encode Sans Expanded": "https://fonts.googleapis.com/css2?family=Encode+Sans+Expanded&display=swap",
    "Encode Sans Semi Condensed": "https://fonts.googleapis.com/css2?family=Encode+Sans+Semi+Condensed&display=swap",
    "Encode Sans Semi Expanded": "https://fonts.googleapis.com/css2?family=Encode+Sans+Semi+Expanded&display=swap",
    "Engagement": "https://fonts.googleapis.com/css2?family=Engagement&display=swap",
    "Englebert": "https://fonts.googleapis.com/css2?family=Englebert&display=swap",
    "Enriqueta": "https://fonts.googleapis.com/css2?family=Enriqueta&display=swap",
    "Erica One": "https://fonts.googleapis.com/css2?family=Erica+One&display=swap",
    "Esteban": "https://fonts.googleapis.com/css2?family=Esteban&display=swap",
    "Euphoria Script": "https://fonts.googleapis.com/css2?family=Euphoria+Script&display=swap",
    "Ewert": "https://fonts.googleapis.com/css2?family=Ewert&display=swap",
    "Exo": "https://fonts.googleapis.com/css2?family=Exo&display=swap",
    "Exo 2": "https://fonts.googleapis.com/css2?family=Exo+2&display=swap",
    "Expletus Sans": "https://fonts.googleapis.com/css2?family=Expletus+Sans&display=swap",
    "Fahkwang": "https://fonts.googleapis.com/css2?family=Fahkwang&display=swap",
    "Fanwood Text": "https://fonts.googleapis.com/css2?family=Fanwood+Text&display=swap",
    "Farro": "https://fonts.googleapis.com/css2?family=Farro&display=swap",
    "Farsan": "https://fonts.googleapis.com/css2?family=Farsan&display=swap",
    "Fascinate": "https://fonts.googleapis.com/css2?family=Fascinate&display=swap",
    "Fascinate Inline": "https://fonts.googleapis.com/css2?family=Fascinate+Inline&display=swap",
    "Faster One": "https://fonts.googleapis.com/css2?family=Faster+One&display=swap",
    "Fasthand": "https://fonts.googleapis.com/css2?family=Fasthand&display=swap",
    "Fauna One": "https://fonts.googleapis.com/css2?family=Fauna+One&display=swap",
    "Faustina": "https://fonts.googleapis.com/css2?family=Faustina&display=swap",
    "Federant": "https://fonts.googleapis.com/css2?family=Federant&display=swap",
    "Federo": "https://fonts.googleapis.com/css2?family=Federo&display=swap",
    "Felipa": "https://fonts.googleapis.com/css2?family=Felipa&display=swap",
    "Fenix": "https://fonts.googleapis.com/css2?family=Fenix&display=swap",
    "Finger Paint": "https://fonts.googleapis.com/css2?family=Finger+Paint&display=swap",
    "Fira Code": "https://fonts.googleapis.com/css2?family=Fira+Code&display=swap",
    "Fira Mono": "https://fonts.googleapis.com/css2?family=Fira+Mono&display=swap",
    "Fira Sans": "https://fonts.googleapis.com/css2?family=Fira+Sans&display=swap",
    "Fira Sans Condensed": "https://fonts.googleapis.com/css2?family=Fira+Sans+Condensed&display=swap",
    "Fira Sans Extra Condensed": "https://fonts.googleapis.com/css2?family=Fira+Sans+Extra+Condensed&display=swap",
    "Fjalla One": "https://fonts.googleapis.com/css2?family=Fjalla+One&display=swap",
    "Fjord One": "https://fonts.googleapis.com/css2?family=Fjord+One&display=swap",
    "Flamenco": "https://fonts.googleapis.com/css2?family=Flamenco&display=swap",
    "Flavors": "https://fonts.googleapis.com/css2?family=Flavors&display=swap",
    "Fondamento": "https://fonts.googleapis.com/css2?family=Fondamento&display=swap",
    "Fontdiner Swanky": "https://fonts.googleapis.com/css2?family=Fontdiner+Swanky&display=swap",
    "Forum": "https://fonts.googleapis.com/css2?family=Forum&display=swap",
    "Francois One": "https://fonts.googleapis.com/css2?family=Francois+One&display=swap",
    "Frank Ruhl Libre": "https://fonts.googleapis.com/css2?family=Frank+Ruhl+Libre&display=swap",
    "Freckle Face": "https://fonts.googleapis.com/css2?family=Freckle+Face&display=swap",
    "Fredericka the Great": "https://fonts.googleapis.com/css2?family=Fredericka+the+Great&display=swap",
    "Fredoka One": "https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap",
    "Freehand": "https://fonts.googleapis.com/css2?family=Freehand&display=swap",
    "Fresca": "https://fonts.googleapis.com/css2?family=Fresca&display=swap",
    "Frijole": "https://fonts.googleapis.com/css2?family=Frijole&display=swap",
    "Fruktur": "https://fonts.googleapis.com/css2?family=Fruktur&display=swap",
    "Fugaz One": "https://fonts.googleapis.com/css2?family=Fugaz+One&display=swap",
    "GFS Didot": "https://fonts.googleapis.com/css2?family=GFS+Didot&display=swap",
    "GFS Neohellenic": "https://fonts.googleapis.com/css2?family=GFS+Neohellenic&display=swap",
    "Gabriela": "https://fonts.googleapis.com/css2?family=Gabriela&display=swap",
    "Gaegu": "https://fonts.googleapis.com/css2?family=Gaegu&display=swap",
    "Gafata": "https://fonts.googleapis.com/css2?family=Gafata&display=swap",
    "Galada": "https://fonts.googleapis.com/css2?family=Galada&display=swap",
    "Galdeano": "https://fonts.googleapis.com/css2?family=Galdeano&display=swap",
    "Galindo": "https://fonts.googleapis.com/css2?family=Galindo&display=swap",
    "Gamja Flower": "https://fonts.googleapis.com/css2?family=Gamja+Flower&display=swap",
    "Gentium Basic": "https://fonts.googleapis.com/css2?family=Gentium+Basic&display=swap",
    "Gentium Book Basic": "https://fonts.googleapis.com/css2?family=Gentium+Book+Basic&display=swap",
    "Geo": "https://fonts.googleapis.com/css2?family=Geo&display=swap",
    "Georgia": null,
    "Geostar": "https://fonts.googleapis.com/css2?family=Geostar&display=swap",
    "Geostar Fill": "https://fonts.googleapis.com/css2?family=Geostar+Fill&display=swap",
    "Germania One": "https://fonts.googleapis.com/css2?family=Germania+One&display=swap",
    "Gidugu": "https://fonts.googleapis.com/css2?family=Gidugu&display=swap",
    "Gilda Display": "https://fonts.googleapis.com/css2?family=Gilda+Display&display=swap",
    "Give You Glory": "https://fonts.googleapis.com/css2?family=Give+You+Glory&display=swap",
    "Glass Antiqua": "https://fonts.googleapis.com/css2?family=Glass+Antiqua&display=swap",
    "Glegoo": "https://fonts.googleapis.com/css2?family=Glegoo&display=swap",
    "Gloria Hallelujah": "https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&display=swap",
    "Goblin One": "https://fonts.googleapis.com/css2?family=Goblin+One&display=swap",
    "Gochi Hand": "https://fonts.googleapis.com/css2?family=Gochi+Hand&display=swap",
    "Gorditas": "https://fonts.googleapis.com/css2?family=Gorditas&display=swap",
    "Gothic A1": "https://fonts.googleapis.com/css2?family=Gothic+A1&display=swap",
    "Goudy Bookletter 1911": "https://fonts.googleapis.com/css2?family=Goudy+Bookletter+1911&display=swap",
    "Graduate": "https://fonts.googleapis.com/css2?family=Graduate&display=swap",
    "Grand Hotel": "https://fonts.googleapis.com/css2?family=Grand+Hotel&display=swap",
    "Gravitas One": "https://fonts.googleapis.com/css2?family=Gravitas+One&display=swap",
    "Great Vibes": "https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap",
    "Grenze": "https://fonts.googleapis.com/css2?family=Grenze&display=swap",
    "Griffy": "https://fonts.googleapis.com/css2?family=Griffy&display=swap",
    "Gruppo": "https://fonts.googleapis.com/css2?family=Gruppo&display=swap",
    "Gudea": "https://fonts.googleapis.com/css2?family=Gudea&display=swap",
    "Gugi": "https://fonts.googleapis.com/css2?family=Gugi&display=swap",
    "Gurajada": "https://fonts.googleapis.com/css2?family=Gurajada&display=swap",
    "Habibi": "https://fonts.googleapis.com/css2?family=Habibi&display=swap",
    "Halant": "https://fonts.googleapis.com/css2?family=Halant&display=swap",
    "Hammersmith One": "https://fonts.googleapis.com/css2?family=Hammersmith+One&display=swap",
    "Hanalei": "https://fonts.googleapis.com/css2?family=Hanalei&display=swap",
    "Hanalei Fill": "https://fonts.googleapis.com/css2?family=Hanalei+Fill&display=swap",
    "Handlee": "https://fonts.googleapis.com/css2?family=Handlee&display=swap",
    "Hanuman": "https://fonts.googleapis.com/css2?family=Hanuman&display=swap",
    "Happy Monkey": "https://fonts.googleapis.com/css2?family=Happy+Monkey&display=swap",
    "Harmattan": "https://fonts.googleapis.com/css2?family=Harmattan&display=swap",
    "Headland One": "https://fonts.googleapis.com/css2?family=Headland+One&display=swap",
    "Heebo": "https://fonts.googleapis.com/css2?family=Heebo&display=swap",
    "Henny Penny": "https://fonts.googleapis.com/css2?family=Henny+Penny&display=swap",
    "Hepta Slab": "https://fonts.googleapis.com/css2?family=Hepta+Slab&display=swap",
    "Herr Von Muellerhoff": "https://fonts.googleapis.com/css2?family=Herr+Von+Muellerhoff&display=swap",
    "Hi Melody": "https://fonts.googleapis.com/css2?family=Hi+Melody&display=swap",
    "Hind": "https://fonts.googleapis.com/css2?family=Hind&display=swap",
    "Hind Guntur": "https://fonts.googleapis.com/css2?family=Hind+Guntur&display=swap",
    "Hind Madurai": "https://fonts.googleapis.com/css2?family=Hind+Madurai&display=swap",
    "Hind Siliguri": "https://fonts.googleapis.com/css2?family=Hind+Siliguri&display=swap",
    "Hind Vadodara": "https://fonts.googleapis.com/css2?family=Hind+Vadodara&display=swap",
    "Holtwood One SC": "https://fonts.googleapis.com/css2?family=Holtwood+One+SC&display=swap",
    "Homemade Apple": "https://fonts.googleapis.com/css2?family=Homemade+Apple&display=swap",
    "Homenaje": "https://fonts.googleapis.com/css2?family=Homenaje&display=swap",
    "IBM Plex Mono": "https://fonts.googleapis.com/css2?family=IBM+Plex+Mono&display=swap",
    "IBM Plex Sans": "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans&display=swap",
    "IBM Plex Sans Condensed": "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Condensed&display=swap",
    "IBM Plex Serif": "https://fonts.googleapis.com/css2?family=IBM+Plex+Serif&display=swap",
    "IM Fell DW Pica": "https://fonts.googleapis.com/css2?family=IM+Fell+DW+Pica&display=swap",
    "IM Fell DW Pica SC": "https://fonts.googleapis.com/css2?family=IM+Fell+DW+Pica+SC&display=swap",
    "IM Fell Double Pica": "https://fonts.googleapis.com/css2?family=IM+Fell+Double+Pica&display=swap",
    "IM Fell Double Pica SC": "https://fonts.googleapis.com/css2?family=IM+Fell+Double+Pica+SC&display=swap",
    "IM Fell English": "https://fonts.googleapis.com/css2?family=IM+Fell+English&display=swap",
    "IM Fell English SC": "https://fonts.googleapis.com/css2?family=IM+Fell+English+SC&display=swap",
    "IM Fell French Canon": "https://fonts.googleapis.com/css2?family=IM+Fell+French+Canon&display=swap",
    "IM Fell French Canon SC": "https://fonts.googleapis.com/css2?family=IM+Fell+French+Canon+SC&display=swap",
    "IM Fell Great Primer": "https://fonts.googleapis.com/css2?family=IM+Fell+Great+Primer&display=swap",
    "IM Fell Great Primer SC": "https://fonts.googleapis.com/css2?family=IM+Fell+Great+Primer+SC&display=swap",
    "Iceberg": "https://fonts.googleapis.com/css2?family=Iceberg&display=swap",
    "Iceland": "https://fonts.googleapis.com/css2?family=Iceland&display=swap",
    "Impact": null,
    "Imprima": "https://fonts.googleapis.com/css2?family=Imprima&display=swap",
    "Inconsolata": "https://fonts.googleapis.com/css2?family=Inconsolata&display=swap",
    "Inder": "https://fonts.googleapis.com/css2?family=Inder&display=swap",
    "Indie Flower": "https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap",
    "Inika": "https://fonts.googleapis.com/css2?family=Inika&display=swap",
    "Inknut Antiqua": "https://fonts.googleapis.com/css2?family=Inknut+Antiqua&display=swap",
    "Irish Grover": "https://fonts.googleapis.com/css2?family=Irish+Grover&display=swap",
    "Istok Web": "https://fonts.googleapis.com/css2?family=Istok+Web&display=swap",
    "Italiana": "https://fonts.googleapis.com/css2?family=Italiana&display=swap",
    "Italianno": "https://fonts.googleapis.com/css2?family=Italianno&display=swap",
    "Itim": "https://fonts.googleapis.com/css2?family=Itim&display=swap",
    "Jacques Francois": "https://fonts.googleapis.com/css2?family=Jacques+Francois&display=swap",
    "Jacques Francois Shadow": "https://fonts.googleapis.com/css2?family=Jacques+Francois+Shadow&display=swap",
    "Jaldi": "https://fonts.googleapis.com/css2?family=Jaldi&display=swap",
    "Jim Nightshade": "https://fonts.googleapis.com/css2?family=Jim+Nightshade&display=swap",
    "Jockey One": "https://fonts.googleapis.com/css2?family=Jockey+One&display=swap",
    "Jolly Lodger": "https://fonts.googleapis.com/css2?family=Jolly+Lodger&display=swap",
    "Jomhuria": "https://fonts.googleapis.com/css2?family=Jomhuria&display=swap",
    "Josefin Sans": "https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap",
    "Josefin Slab": "https://fonts.googleapis.com/css2?family=Josefin+Slab&display=swap",
    "Joti One": "https://fonts.googleapis.com/css2?family=Joti+One&display=swap",
    "Jua": "https://fonts.googleapis.com/css2?family=Jua&display=swap",
    "Judson": "https://fonts.googleapis.com/css2?family=Judson&display=swap",
    "Julee": "https://fonts.googleapis.com/css2?family=Julee&display=swap",
    "Julius Sans One": "https://fonts.googleapis.com/css2?family=Julius+Sans+One&display=swap",
    "Junge": "https://fonts.googleapis.com/css2?family=Junge&display=swap",
    "Jura": "https://fonts.googleapis.com/css2?family=Jura&display=swap",
    "Just Another Hand": "https://fonts.googleapis.com/css2?family=Just+Another+Hand&display=swap",
    "Just Me Again Down Here": "https://fonts.googleapis.com/css2?family=Just+Me+Again+Down+Here&display=swap",
    "K2D": "https://fonts.googleapis.com/css2?family=K2D&display=swap",
    "Kadwa": "https://fonts.googleapis.com/css2?family=Kadwa&display=swap",
    "Kalam": "https://fonts.googleapis.com/css2?family=Kalam&display=swap",
    "Kameron": "https://fonts.googleapis.com/css2?family=Kameron&display=swap",
    "Kanit": "https://fonts.googleapis.com/css2?family=Kanit&display=swap",
    "Kantumruy": "https://fonts.googleapis.com/css2?family=Kantumruy&display=swap",
    "Karla": "https://fonts.googleapis.com/css2?family=Karla&display=swap",
    "Karma": "https://fonts.googleapis.com/css2?family=Karma&display=swap",
    "Katibeh": "https://fonts.googleapis.com/css2?family=Katibeh&display=swap",
    "Kaushan Script": "https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap",
    "Kavivanar": "https://fonts.googleapis.com/css2?family=Kavivanar&display=swap",
    "Kavoon": "https://fonts.googleapis.com/css2?family=Kavoon&display=swap",
    "Kdam Thmor": "https://fonts.googleapis.com/css2?family=Kdam+Thmor&display=swap",
    "Keania One": "https://fonts.googleapis.com/css2?family=Keania+One&display=swap",
    "Kelly Slab": "https://fonts.googleapis.com/css2?family=Kelly+Slab&display=swap",
    "Kenia": "https://fonts.googleapis.com/css2?family=Kenia&display=swap",
    "Khand": "https://fonts.googleapis.com/css2?family=Khand&display=swap",
    "Khmer": "https://fonts.googleapis.com/css2?family=Khmer&display=swap",
    "Khula": "https://fonts.googleapis.com/css2?family=Khula&display=swap",
    "Kirang Haerang": "https://fonts.googleapis.com/css2?family=Kirang+Haerang&display=swap",
    "Kite One": "https://fonts.googleapis.com/css2?family=Kite+One&display=swap",
    "Knewave": "https://fonts.googleapis.com/css2?family=Knewave&display=swap",
    "KoHo": "https://fonts.googleapis.com/css2?family=KoHo&display=swap",
    "Kodchasan": "https://fonts.googleapis.com/css2?family=Kodchasan&display=swap",
    "Kosugi": "https://fonts.googleapis.com/css2?family=Kosugi&display=swap",
    "Kosugi Maru": "https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap",
    "Kotta One": "https://fonts.googleapis.com/css2?family=Kotta+One&display=swap",
    "Koulen": "https://fonts.googleapis.com/css2?family=Koulen&display=swap",
    "Kranky": "https://fonts.googleapis.com/css2?family=Kranky&display=swap",
    "Kreon": "https://fonts.googleapis.com/css2?family=Kreon&display=swap",
    "Kristi": "https://fonts.googleapis.com/css2?family=Kristi&display=swap",
    "Krona One": "https://fonts.googleapis.com/css2?family=Krona+One&display=swap",
    "Krub": "https://fonts.googleapis.com/css2?family=Krub&display=swap",
    "Kumar One": "https://fonts.googleapis.com/css2?family=Kumar+One&display=swap",
    "Kumar One Outline": "https://fonts.googleapis.com/css2?family=Kumar+One+Outline&display=swap",
    "Kurale": "https://fonts.googleapis.com/css2?family=Kurale&display=swap",
    "La Belle Aurore": "https://fonts.googleapis.com/css2?family=La+Belle+Aurore&display=swap",
    "Lacquer": "https://fonts.googleapis.com/css2?family=Lacquer&display=swap",
    "Laila": "https://fonts.googleapis.com/css2?family=Laila&display=swap",
    "Lakki Reddy": "https://fonts.googleapis.com/css2?family=Lakki+Reddy&display=swap",
    "Lalezar": "https://fonts.googleapis.com/css2?family=Lalezar&display=swap",
    "Lancelot": "https://fonts.googleapis.com/css2?family=Lancelot&display=swap",
    "Lateef": "https://fonts.googleapis.com/css2?family=Lateef&display=swap",
    "Lato": "https://fonts.googleapis.com/css2?family=Lato&display=swap",
    "League Script": "https://fonts.googleapis.com/css2?family=League+Script&display=swap",
    "Leckerli One": "https://fonts.googleapis.com/css2?family=Leckerli+One&display=swap",
    "Ledger": "https://fonts.googleapis.com/css2?family=Ledger&display=swap",
    "Lekton": "https://fonts.googleapis.com/css2?family=Lekton&display=swap",
    "Lemon": "https://fonts.googleapis.com/css2?family=Lemon&display=swap",
    "Lemonada": "https://fonts.googleapis.com/css2?family=Lemonada&display=swap",
    "Lexend Deca": "https://fonts.googleapis.com/css2?family=Lexend+Deca&display=swap",
    "Lexend Exa": "https://fonts.googleapis.com/css2?family=Lexend+Exa&display=swap",
    "Lexend Giga": "https://fonts.googleapis.com/css2?family=Lexend+Giga&display=swap",
    "Lexend Mega": "https://fonts.googleapis.com/css2?family=Lexend+Mega&display=swap",
    "Lexend Peta": "https://fonts.googleapis.com/css2?family=Lexend+Peta&display=swap",
    "Lexend Tera": "https://fonts.googleapis.com/css2?family=Lexend+Tera&display=swap",
    "Lexend Zetta": "https://fonts.googleapis.com/css2?family=Lexend+Zetta&display=swap",
    "Libre Barcode 128": "https://fonts.googleapis.com/css2?family=Libre+Barcode+128&display=swap",
    "Libre Barcode 128 Text": "https://fonts.googleapis.com/css2?family=Libre+Barcode+128+Text&display=swap",
    "Libre Barcode 39": "https://fonts.googleapis.com/css2?family=Libre+Barcode+39&display=swap",
    "Libre Barcode 39 Extended": "https://fonts.googleapis.com/css2?family=Libre+Barcode+39+Extended&display=swap",
    "Libre Barcode 39 Extended Text": "https://fonts.googleapis.com/css2?family=Libre+Barcode+39+Extended+Text&display=swap",
    "Libre Barcode 39 Text": "https://fonts.googleapis.com/css2?family=Libre+Barcode+39+Text&display=swap",
    "Libre Baskerville": "https://fonts.googleapis.com/css2?family=Libre+Baskerville&display=swap",
    "Libre Caslon Display": "https://fonts.googleapis.com/css2?family=Libre+Caslon+Display&display=swap",
    "Libre Caslon Text": "https://fonts.googleapis.com/css2?family=Libre+Caslon+Text&display=swap",
    "Libre Franklin": "https://fonts.googleapis.com/css2?family=Libre+Franklin&display=swap",
    "Life Savers": "https://fonts.googleapis.com/css2?family=Life+Savers&display=swap",
    "Lilita One": "https://fonts.googleapis.com/css2?family=Lilita+One&display=swap",
    "Lily Script One": "https://fonts.googleapis.com/css2?family=Lily+Script+One&display=swap",
    "Limelight": "https://fonts.googleapis.com/css2?family=Limelight&display=swap",
    "Linden Hill": "https://fonts.googleapis.com/css2?family=Linden+Hill&display=swap",
    "Literata": "https://fonts.googleapis.com/css2?family=Literata&display=swap",
    "Liu Jian Mao Cao": "https://fonts.googleapis.com/css2?family=Liu+Jian+Mao+Cao&display=swap",
    "Livvic": "https://fonts.googleapis.com/css2?family=Livvic&display=swap",
    "Lobster": "https://fonts.googleapis.com/css2?family=Lobster&display=swap",
    "Lobster Two": "https://fonts.googleapis.com/css2?family=Lobster+Two&display=swap",
    "Londrina Outline": "https://fonts.googleapis.com/css2?family=Londrina+Outline&display=swap",
    "Londrina Shadow": "https://fonts.googleapis.com/css2?family=Londrina+Shadow&display=swap",
    "Londrina Sketch": "https://fonts.googleapis.com/css2?family=Londrina+Sketch&display=swap",
    "Londrina Solid": "https://fonts.googleapis.com/css2?family=Londrina+Solid&display=swap",
    "Long Cang": "https://fonts.googleapis.com/css2?family=Long+Cang&display=swap",
    "Lora": "https://fonts.googleapis.com/css2?family=Lora&display=swap",
    "Love Ya Like A Sister": "https://fonts.googleapis.com/css2?family=Love+Ya+Like+A+Sister&display=swap",
    "Loved by the King": "https://fonts.googleapis.com/css2?family=Loved+by+the+King&display=swap",
    "Lovers Quarrel": "https://fonts.googleapis.com/css2?family=Lovers+Quarrel&display=swap",
    "Luckiest Guy": "https://fonts.googleapis.com/css2?family=Luckiest+Guy&display=swap",
    "Lucida Console": null,
    "Lucida Sans Unicode": null,
    "Lusitana": "https://fonts.googleapis.com/css2?family=Lusitana&display=swap",
    "Lustria": "https://fonts.googleapis.com/css2?family=Lustria&display=swap",
    "M PLUS 1p": "https://fonts.googleapis.com/css2?family=M+PLUS+1p&display=swap",
    "M PLUS Rounded 1c": "https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c&display=swap",
    "Ma Shan Zheng": "https://fonts.googleapis.com/css2?family=Ma+Shan+Zheng&display=swap",
    "Macondo": "https://fonts.googleapis.com/css2?family=Macondo&display=swap",
    "Macondo Swash Caps": "https://fonts.googleapis.com/css2?family=Macondo+Swash+Caps&display=swap",
    "Mada": "https://fonts.googleapis.com/css2?family=Mada&display=swap",
    "Magra": "https://fonts.googleapis.com/css2?family=Magra&display=swap",
    "Maiden Orange": "https://fonts.googleapis.com/css2?family=Maiden+Orange&display=swap",
    "Maitree": "https://fonts.googleapis.com/css2?family=Maitree&display=swap",
    "Major Mono Display": "https://fonts.googleapis.com/css2?family=Major+Mono+Display&display=swap",
    "Mako": "https://fonts.googleapis.com/css2?family=Mako&display=swap",
    "Mali": "https://fonts.googleapis.com/css2?family=Mali&display=swap",
    "Mallanna": "https://fonts.googleapis.com/css2?family=Mallanna&display=swap",
    "Mandali": "https://fonts.googleapis.com/css2?family=Mandali&display=swap",
    "Manuale": "https://fonts.googleapis.com/css2?family=Manuale&display=swap",
    "Marcellus": "https://fonts.googleapis.com/css2?family=Marcellus&display=swap",
    "Marcellus SC": "https://fonts.googleapis.com/css2?family=Marcellus+SC&display=swap",
    "Marck Script": "https://fonts.googleapis.com/css2?family=Marck+Script&display=swap",
    "Margarine": "https://fonts.googleapis.com/css2?family=Margarine&display=swap",
    "Markazi Text": "https://fonts.googleapis.com/css2?family=Markazi+Text&display=swap",
    "Marko One": "https://fonts.googleapis.com/css2?family=Marko+One&display=swap",
    "Marmelad": "https://fonts.googleapis.com/css2?family=Marmelad&display=swap",
    "Martel": "https://fonts.googleapis.com/css2?family=Martel&display=swap",
    "Martel Sans": "https://fonts.googleapis.com/css2?family=Martel+Sans&display=swap",
    "Marvel": "https://fonts.googleapis.com/css2?family=Marvel&display=swap",
    "Mate": "https://fonts.googleapis.com/css2?family=Mate&display=swap",
    "Mate SC": "https://fonts.googleapis.com/css2?family=Mate+SC&display=swap",
    "Maven Pro": "https://fonts.googleapis.com/css2?family=Maven+Pro&display=swap",
    "McLaren": "https://fonts.googleapis.com/css2?family=McLaren&display=swap",
    "Meddon": "https://fonts.googleapis.com/css2?family=Meddon&display=swap",
    "MedievalSharp": "https://fonts.googleapis.com/css2?family=MedievalSharp&display=swap",
    "Medula One": "https://fonts.googleapis.com/css2?family=Medula+One&display=swap",
    "Meera Inimai": "https://fonts.googleapis.com/css2?family=Meera+Inimai&display=swap",
    "Megrim": "https://fonts.googleapis.com/css2?family=Megrim&display=swap",
    "Meie Script": "https://fonts.googleapis.com/css2?family=Meie+Script&display=swap",
    "Merienda": "https://fonts.googleapis.com/css2?family=Merienda&display=swap",
    "Merienda One": "https://fonts.googleapis.com/css2?family=Merienda+One&display=swap",
    "Merriweather": "https://fonts.googleapis.com/css2?family=Merriweather&display=swap",
    "Merriweather Sans": "https://fonts.googleapis.com/css2?family=Merriweather+Sans&display=swap",
    "Metal": "https://fonts.googleapis.com/css2?family=Metal&display=swap",
    "Metal Mania": "https://fonts.googleapis.com/css2?family=Metal+Mania&display=swap",
    "Metamorphous": "https://fonts.googleapis.com/css2?family=Metamorphous&display=swap",
    "Metrophobic": "https://fonts.googleapis.com/css2?family=Metrophobic&display=swap",
    "Michroma": "https://fonts.googleapis.com/css2?family=Michroma&display=swap",
    "Milonga": "https://fonts.googleapis.com/css2?family=Milonga&display=swap",
    "Miltonian": "https://fonts.googleapis.com/css2?family=Miltonian&display=swap",
    "Miltonian Tattoo": "https://fonts.googleapis.com/css2?family=Miltonian+Tattoo&display=swap",
    "Mina": "https://fonts.googleapis.com/css2?family=Mina&display=swap",
    "Miniver": "https://fonts.googleapis.com/css2?family=Miniver&display=swap",
    "Miriam Libre": "https://fonts.googleapis.com/css2?family=Miriam+Libre&display=swap",
    "Mirza": "https://fonts.googleapis.com/css2?family=Mirza&display=swap",
    "Miss Fajardose": "https://fonts.googleapis.com/css2?family=Miss+Fajardose&display=swap",
    "Mitr": "https://fonts.googleapis.com/css2?family=Mitr&display=swap",
    "Modak": "https://fonts.googleapis.com/css2?family=Modak&display=swap",
    "Modern Antiqua": "https://fonts.googleapis.com/css2?family=Modern+Antiqua&display=swap",
    "Mogra": "https://fonts.googleapis.com/css2?family=Mogra&display=swap",
    "Molengo": "https://fonts.googleapis.com/css2?family=Molengo&display=swap",
    "Molle": "https://fonts.googleapis.com/css2?family=Molle&display=swap",
    "Monda": "https://fonts.googleapis.com/css2?family=Monda&display=swap",
    "Monofett": "https://fonts.googleapis.com/css2?family=Monofett&display=swap",
    "Monoton": "https://fonts.googleapis.com/css2?family=Monoton&display=swap",
    "Monsieur La Doulaise": "https://fonts.googleapis.com/css2?family=Monsieur+La+Doulaise&display=swap",
    "Montaga": "https://fonts.googleapis.com/css2?family=Montaga&display=swap",
    "Montez": "https://fonts.googleapis.com/css2?family=Montez&display=swap",
    "Montserrat": "https://fonts.googleapis.com/css2?family=Montserrat&display=swap",
    "Montserrat Alternates": "https://fonts.googleapis.com/css2?family=Montserrat+Alternates&display=swap",
    "Montserrat Subrayada": "https://fonts.googleapis.com/css2?family=Montserrat+Subrayada&display=swap",
    "Moul": "https://fonts.googleapis.com/css2?family=Moul&display=swap",
    "Moulpali": "https://fonts.googleapis.com/css2?family=Moulpali&display=swap",
    "Mountains of Christmas": "https://fonts.googleapis.com/css2?family=Mountains+of+Christmas&display=swap",
    "Mouse Memoirs": "https://fonts.googleapis.com/css2?family=Mouse+Memoirs&display=swap",
    "Mr Bedfort": "https://fonts.googleapis.com/css2?family=Mr+Bedfort&display=swap",
    "Mr Dafoe": "https://fonts.googleapis.com/css2?family=Mr+Dafoe&display=swap",
    "Mr De Haviland": "https://fonts.googleapis.com/css2?family=Mr+De+Haviland&display=swap",
    "Mrs Saint Delafield": "https://fonts.googleapis.com/css2?family=Mrs+Saint+Delafield&display=swap",
    "Mrs Sheppards": "https://fonts.googleapis.com/css2?family=Mrs+Sheppards&display=swap",
    "Mukta": "https://fonts.googleapis.com/css2?family=Mukta&display=swap",
    "Mukta Mahee": "https://fonts.googleapis.com/css2?family=Mukta+Mahee&display=swap",
    "Mukta Malar": "https://fonts.googleapis.com/css2?family=Mukta+Malar&display=swap",
    "Mukta Vaani": "https://fonts.googleapis.com/css2?family=Mukta+Vaani&display=swap",
    "Muli": "https://fonts.googleapis.com/css2?family=Muli&display=swap",
    "Mystery Quest": "https://fonts.googleapis.com/css2?family=Mystery+Quest&display=swap",
    "NTR": "https://fonts.googleapis.com/css2?family=NTR&display=swap",
    "Nanum Brush Script": "https://fonts.googleapis.com/css2?family=Nanum+Brush+Script&display=swap",
    "Nanum Gothic": "https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap",
    "Nanum Gothic Coding": "https://fonts.googleapis.com/css2?family=Nanum+Gothic+Coding&display=swap",
    "Nanum Myeongjo": "https://fonts.googleapis.com/css2?family=Nanum+Myeongjo&display=swap",
    "Nanum Pen Script": "https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap",
    "Neucha": "https://fonts.googleapis.com/css2?family=Neucha&display=swap",
    "Neuton": "https://fonts.googleapis.com/css2?family=Neuton&display=swap",
    "New Rocker": "https://fonts.googleapis.com/css2?family=New+Rocker&display=swap",
    "News Cycle": "https://fonts.googleapis.com/css2?family=News+Cycle&display=swap",
    "Niconne": "https://fonts.googleapis.com/css2?family=Niconne&display=swap",
    "Niramit": "https://fonts.googleapis.com/css2?family=Niramit&display=swap",
    "Nixie One": "https://fonts.googleapis.com/css2?family=Nixie+One&display=swap",
    "Nobile": "https://fonts.googleapis.com/css2?family=Nobile&display=swap",
    "Nokora": "https://fonts.googleapis.com/css2?family=Nokora&display=swap",
    "Norican": "https://fonts.googleapis.com/css2?family=Norican&display=swap",
    "Nosifer": "https://fonts.googleapis.com/css2?family=Nosifer&display=swap",
    "Notable": "https://fonts.googleapis.com/css2?family=Notable&display=swap",
    "Nothing You Could Do": "https://fonts.googleapis.com/css2?family=Nothing+You+Could+Do&display=swap",
    "Noticia Text": "https://fonts.googleapis.com/css2?family=Noticia+Text&display=swap",
    "Noto Sans": "https://fonts.googleapis.com/css2?family=Noto+Sans&display=swap",
    "Noto Sans HK": "https://fonts.googleapis.com/css2?family=Noto+Sans+HK&display=swap",
    "Noto Sans JP": "https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap",
    "Noto Sans KR": "https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap",
    "Noto Sans SC": "https://fonts.googleapis.com/css2?family=Noto+Sans+SC&display=swap",
    "Noto Sans TC": "https://fonts.googleapis.com/css2?family=Noto+Sans+TC&display=swap",
    "Noto Serif": "https://fonts.googleapis.com/css2?family=Noto+Serif&display=swap",
    "Noto Serif JP": "https://fonts.googleapis.com/css2?family=Noto+Serif+JP&display=swap",
    "Noto Serif KR": "https://fonts.googleapis.com/css2?family=Noto+Serif+KR&display=swap",
    "Noto Serif SC": "https://fonts.googleapis.com/css2?family=Noto+Serif+SC&display=swap",
    "Noto Serif TC": "https://fonts.googleapis.com/css2?family=Noto+Serif+TC&display=swap",
    "Nova Cut": "https://fonts.googleapis.com/css2?family=Nova+Cut&display=swap",
    "Nova Flat": "https://fonts.googleapis.com/css2?family=Nova+Flat&display=swap",
    "Nova Mono": "https://fonts.googleapis.com/css2?family=Nova+Mono&display=swap",
    "Nova Oval": "https://fonts.googleapis.com/css2?family=Nova+Oval&display=swap",
    "Nova Round": "https://fonts.googleapis.com/css2?family=Nova+Round&display=swap",
    "Nova Script": "https://fonts.googleapis.com/css2?family=Nova+Script&display=swap",
    "Nova Slim": "https://fonts.googleapis.com/css2?family=Nova+Slim&display=swap",
    "Nova Square": "https://fonts.googleapis.com/css2?family=Nova+Square&display=swap",
    "Numans": "https://fonts.googleapis.com/css2?family=Numans&display=swap",
    "Nunito": "https://fonts.googleapis.com/css2?family=Nunito&display=swap",
    "Nunito Sans": "https://fonts.googleapis.com/css2?family=Nunito+Sans&display=swap",
    "Odor Mean Chey": "https://fonts.googleapis.com/css2?family=Odor+Mean+Chey&display=swap",
    "Offside": "https://fonts.googleapis.com/css2?family=Offside&display=swap",
    "Old Standard TT": "https://fonts.googleapis.com/css2?family=Old+Standard+TT&display=swap",
    "Oldenburg": "https://fonts.googleapis.com/css2?family=Oldenburg&display=swap",
    "Oleo Script": "https://fonts.googleapis.com/css2?family=Oleo+Script&display=swap",
    "Oleo Script Swash Caps": "https://fonts.googleapis.com/css2?family=Oleo+Script+Swash+Caps&display=swap",
    "Open Sans": "https://fonts.googleapis.com/css2?family=Open+Sans&display=swap",
    "Open Sans Condensed": "https://fonts.googleapis.com/css2?family=Open+Sans+Condensed&display=swap",
    "Oranienbaum": "https://fonts.googleapis.com/css2?family=Oranienbaum&display=swap",
    "Orbitron": "https://fonts.googleapis.com/css2?family=Orbitron&display=swap",
    "Oregano": "https://fonts.googleapis.com/css2?family=Oregano&display=swap",
    "Orienta": "https://fonts.googleapis.com/css2?family=Orienta&display=swap",
    "Original Surfer": "https://fonts.googleapis.com/css2?family=Original+Surfer&display=swap",
    "Oswald": "https://fonts.googleapis.com/css2?family=Oswald&display=swap",
    "Over the Rainbow": "https://fonts.googleapis.com/css2?family=Over+the+Rainbow&display=swap",
    "Overlock": "https://fonts.googleapis.com/css2?family=Overlock&display=swap",
    "Overlock SC": "https://fonts.googleapis.com/css2?family=Overlock+SC&display=swap",
    "Overpass": "https://fonts.googleapis.com/css2?family=Overpass&display=swap",
    "Overpass Mono": "https://fonts.googleapis.com/css2?family=Overpass+Mono&display=swap",
    "Ovo": "https://fonts.googleapis.com/css2?family=Ovo&display=swap",
    "Oxygen": "https://fonts.googleapis.com/css2?family=Oxygen&display=swap",
    "Oxygen Mono": "https://fonts.googleapis.com/css2?family=Oxygen+Mono&display=swap",
    "PT Mono": "https://fonts.googleapis.com/css2?family=PT+Mono&display=swap",
    "PT Sans": "https://fonts.googleapis.com/css2?family=PT+Sans&display=swap",
    "PT Sans Caption": "https://fonts.googleapis.com/css2?family=PT+Sans+Caption&display=swap",
    "PT Sans Narrow": "https://fonts.googleapis.com/css2?family=PT+Sans+Narrow&display=swap",
    "PT Serif": "https://fonts.googleapis.com/css2?family=PT+Serif&display=swap",
    "PT Serif Caption": "https://fonts.googleapis.com/css2?family=PT+Serif+Caption&display=swap",
    "Pacifico": "https://fonts.googleapis.com/css2?family=Pacifico&display=swap",
    "Padauk": "https://fonts.googleapis.com/css2?family=Padauk&display=swap",
    "Palanquin": "https://fonts.googleapis.com/css2?family=Palanquin&display=swap",
    "Palanquin Dark": "https://fonts.googleapis.com/css2?family=Palanquin+Dark&display=swap",
    "Pangolin": "https://fonts.googleapis.com/css2?family=Pangolin&display=swap",
    "Paprika": "https://fonts.googleapis.com/css2?family=Paprika&display=swap",
    "Parisienne": "https://fonts.googleapis.com/css2?family=Parisienne&display=swap",
    "Passero One": "https://fonts.googleapis.com/css2?family=Passero+One&display=swap",
    "Passion One": "https://fonts.googleapis.com/css2?family=Passion+One&display=swap",
    "Pathway Gothic One": "https://fonts.googleapis.com/css2?family=Pathway+Gothic+One&display=swap",
    "Patrick Hand": "https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap",
    "Patrick Hand SC": "https://fonts.googleapis.com/css2?family=Patrick+Hand+SC&display=swap",
    "Pattaya": "https://fonts.googleapis.com/css2?family=Pattaya&display=swap",
    "Patua One": "https://fonts.googleapis.com/css2?family=Patua+One&display=swap",
    "Pavanam": "https://fonts.googleapis.com/css2?family=Pavanam&display=swap",
    "Paytone One": "https://fonts.googleapis.com/css2?family=Paytone+One&display=swap",
    "Peddana": "https://fonts.googleapis.com/css2?family=Peddana&display=swap",
    "Peralta": "https://fonts.googleapis.com/css2?family=Peralta&display=swap",
    "Permanent Marker": "https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap",
    "Petit Formal Script": "https://fonts.googleapis.com/css2?family=Petit+Formal+Script&display=swap",
    "Petrona": "https://fonts.googleapis.com/css2?family=Petrona&display=swap",
    "Philosopher": "https://fonts.googleapis.com/css2?family=Philosopher&display=swap",
    "Piedra": "https://fonts.googleapis.com/css2?family=Piedra&display=swap",
    "Pinyon Script": "https://fonts.googleapis.com/css2?family=Pinyon+Script&display=swap",
    "Pirata One": "https://fonts.googleapis.com/css2?family=Pirata+One&display=swap",
    "Plaster": "https://fonts.googleapis.com/css2?family=Plaster&display=swap",
    "Play": "https://fonts.googleapis.com/css2?family=Play&display=swap",
    "Playball": "https://fonts.googleapis.com/css2?family=Playball&display=swap",
    "Playfair Display": "https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap",
    "Playfair Display SC": "https://fonts.googleapis.com/css2?family=Playfair+Display+SC&display=swap",
    "Podkova": "https://fonts.googleapis.com/css2?family=Podkova&display=swap",
    "Poiret One": "https://fonts.googleapis.com/css2?family=Poiret+One&display=swap",
    "Poller One": "https://fonts.googleapis.com/css2?family=Poller+One&display=swap",
    "Poly": "https://fonts.googleapis.com/css2?family=Poly&display=swap",
    "Pompiere": "https://fonts.googleapis.com/css2?family=Pompiere&display=swap",
    "Pontano Sans": "https://fonts.googleapis.com/css2?family=Pontano+Sans&display=swap",
    "Poor Story": "https://fonts.googleapis.com/css2?family=Poor+Story&display=swap",
    "Poppins": "https://fonts.googleapis.com/css2?family=Poppins&display=swap",
    "Port Lligat Sans": "https://fonts.googleapis.com/css2?family=Port+Lligat+Sans&display=swap",
    "Port Lligat Slab": "https://fonts.googleapis.com/css2?family=Port+Lligat+Slab&display=swap",
    "Pragati Narrow": "https://fonts.googleapis.com/css2?family=Pragati+Narrow&display=swap",
    "Prata": "https://fonts.googleapis.com/css2?family=Prata&display=swap",
    "Preahvihear": "https://fonts.googleapis.com/css2?family=Preahvihear&display=swap",
    "Press Start 2P": "https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap",
    "Pridi": "https://fonts.googleapis.com/css2?family=Pridi&display=swap",
    "Princess Sofia": "https://fonts.googleapis.com/css2?family=Princess+Sofia&display=swap",
    "Prociono": "https://fonts.googleapis.com/css2?family=Prociono&display=swap",
    "Prompt": "https://fonts.googleapis.com/css2?family=Prompt&display=swap",
    "Prosto One": "https://fonts.googleapis.com/css2?family=Prosto+One&display=swap",
    "Proza Libre": "https://fonts.googleapis.com/css2?family=Proza+Libre&display=swap",
    "Puritan": "https://fonts.googleapis.com/css2?family=Puritan&display=swap",
    "Purple Purse": "https://fonts.googleapis.com/css2?family=Purple+Purse&display=swap",
    "Quando": "https://fonts.googleapis.com/css2?family=Quando&display=swap",
    "Quantico": "https://fonts.googleapis.com/css2?family=Quantico&display=swap",
    "Quattrocento": "https://fonts.googleapis.com/css2?family=Quattrocento&display=swap",
    "Quattrocento Sans": "https://fonts.googleapis.com/css2?family=Quattrocento+Sans&display=swap",
    "Questrial": "https://fonts.googleapis.com/css2?family=Questrial&display=swap",
    "Quicksand": "https://fonts.googleapis.com/css2?family=Quicksand&display=swap",
    "Quintessential": "https://fonts.googleapis.com/css2?family=Quintessential&display=swap",
    "Qwigley": "https://fonts.googleapis.com/css2?family=Qwigley&display=swap",
    "Racing Sans One": "https://fonts.googleapis.com/css2?family=Racing+Sans+One&display=swap",
    "Radley": "https://fonts.googleapis.com/css2?family=Radley&display=swap",
    "Rajdhani": "https://fonts.googleapis.com/css2?family=Rajdhani&display=swap",
    "Rakkas": "https://fonts.googleapis.com/css2?family=Rakkas&display=swap",
    "Raleway": "https://fonts.googleapis.com/css2?family=Raleway&display=swap",
    "Raleway Dots": "https://fonts.googleapis.com/css2?family=Raleway+Dots&display=swap",
    "Ramabhadra": "https://fonts.googleapis.com/css2?family=Ramabhadra&display=swap",
    "Ramaraja": "https://fonts.googleapis.com/css2?family=Ramaraja&display=swap",
    "Rambla": "https://fonts.googleapis.com/css2?family=Rambla&display=swap",
    "Rammetto One": "https://fonts.googleapis.com/css2?family=Rammetto+One&display=swap",
    "Ranchers": "https://fonts.googleapis.com/css2?family=Ranchers&display=swap",
    "Rancho": "https://fonts.googleapis.com/css2?family=Rancho&display=swap",
    "Ranga": "https://fonts.googleapis.com/css2?family=Ranga&display=swap",
    "Rasa": "https://fonts.googleapis.com/css2?family=Rasa&display=swap",
    "Rationale": "https://fonts.googleapis.com/css2?family=Rationale&display=swap",
    "Ravi Prakash": "https://fonts.googleapis.com/css2?family=Ravi+Prakash&display=swap",
    "Red Hat Display": "https://fonts.googleapis.com/css2?family=Red+Hat+Display&display=swap",
    "Red Hat Text": "https://fonts.googleapis.com/css2?family=Red+Hat+Text&display=swap",
    "Redressed": "https://fonts.googleapis.com/css2?family=Redressed&display=swap",
    "Reem Kufi": "https://fonts.googleapis.com/css2?family=Reem+Kufi&display=swap",
    "Reenie Beanie": "https://fonts.googleapis.com/css2?family=Reenie+Beanie&display=swap",
    "Revalia": "https://fonts.googleapis.com/css2?family=Revalia&display=swap",
    "Rhodium Libre": "https://fonts.googleapis.com/css2?family=Rhodium+Libre&display=swap",
    "Ribeye": "https://fonts.googleapis.com/css2?family=Ribeye&display=swap",
    "Ribeye Marrow": "https://fonts.googleapis.com/css2?family=Ribeye+Marrow&display=swap",
    "Righteous": "https://fonts.googleapis.com/css2?family=Righteous&display=swap",
    "Risque": "https://fonts.googleapis.com/css2?family=Risque&display=swap",
    "Roboto": "https://fonts.googleapis.com/css2?family=Roboto&display=swap",
    "Roboto Condensed": "https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap",
    "Roboto Mono": "https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap",
    "Roboto Slab": "https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap",
    "Rochester": "https://fonts.googleapis.com/css2?family=Rochester&display=swap",
    "Rock Salt": "https://fonts.googleapis.com/css2?family=Rock+Salt&display=swap",
    "Rokkitt": "https://fonts.googleapis.com/css2?family=Rokkitt&display=swap",
    "Romanesco": "https://fonts.googleapis.com/css2?family=Romanesco&display=swap",
    "Ropa Sans": "https://fonts.googleapis.com/css2?family=Ropa+Sans&display=swap",
    "Rosario": "https://fonts.googleapis.com/css2?family=Rosario&display=swap",
    "Rosarivo": "https://fonts.googleapis.com/css2?family=Rosarivo&display=swap",
    "Rouge Script": "https://fonts.googleapis.com/css2?family=Rouge+Script&display=swap",
    "Rozha One": "https://fonts.googleapis.com/css2?family=Rozha+One&display=swap",
    "Rubik": "https://fonts.googleapis.com/css2?family=Rubik&display=swap",
    "Rubik Mono One": "https://fonts.googleapis.com/css2?family=Rubik+Mono+One&display=swap",
    "Ruda": "https://fonts.googleapis.com/css2?family=Ruda&display=swap",
    "Rufina": "https://fonts.googleapis.com/css2?family=Rufina&display=swap",
    "Ruge Boogie": "https://fonts.googleapis.com/css2?family=Ruge+Boogie&display=swap",
    "Ruluko": "https://fonts.googleapis.com/css2?family=Ruluko&display=swap",
    "Rum Raisin": "https://fonts.googleapis.com/css2?family=Rum+Raisin&display=swap",
    "Ruslan Display": "https://fonts.googleapis.com/css2?family=Ruslan+Display&display=swap",
    "Russo One": "https://fonts.googleapis.com/css2?family=Russo+One&display=swap",
    "Ruthie": "https://fonts.googleapis.com/css2?family=Ruthie&display=swap",
    "Rye": "https://fonts.googleapis.com/css2?family=Rye&display=swap",
    "Sacramento": "https://fonts.googleapis.com/css2?family=Sacramento&display=swap",
    "Sahitya": "https://fonts.googleapis.com/css2?family=Sahitya&display=swap",
    "Sail": "https://fonts.googleapis.com/css2?family=Sail&display=swap",
    "Saira": "https://fonts.googleapis.com/css2?family=Saira&display=swap",
    "Saira Condensed": "https://fonts.googleapis.com/css2?family=Saira+Condensed&display=swap",
    "Saira Extra Condensed": "https://fonts.googleapis.com/css2?family=Saira+Extra+Condensed&display=swap",
    "Saira Semi Condensed": "https://fonts.googleapis.com/css2?family=Saira+Semi+Condensed&display=swap",
    "Saira Stencil One": "https://fonts.googleapis.com/css2?family=Saira+Stencil+One&display=swap",
    "Salsa": "https://fonts.googleapis.com/css2?family=Salsa&display=swap",
    "Sanchez": "https://fonts.googleapis.com/css2?family=Sanchez&display=swap",
    "Sancreek": "https://fonts.googleapis.com/css2?family=Sancreek&display=swap",
    "Sansita": "https://fonts.googleapis.com/css2?family=Sansita&display=swap",
    "Sarabun": "https://fonts.googleapis.com/css2?family=Sarabun&display=swap",
    "Sarala": "https://fonts.googleapis.com/css2?family=Sarala&display=swap",
    "Sarina": "https://fonts.googleapis.com/css2?family=Sarina&display=swap",
    "Sarpanch": "https://fonts.googleapis.com/css2?family=Sarpanch&display=swap",
    "Satisfy": "https://fonts.googleapis.com/css2?family=Satisfy&display=swap",
    "Sawarabi Gothic": "https://fonts.googleapis.com/css2?family=Sawarabi+Gothic&display=swap",
    "Sawarabi Mincho": "https://fonts.googleapis.com/css2?family=Sawarabi+Mincho&display=swap",
    "Scada": "https://fonts.googleapis.com/css2?family=Scada&display=swap",
    "Scheherazade": "https://fonts.googleapis.com/css2?family=Scheherazade&display=swap",
    "Schoolbell": "https://fonts.googleapis.com/css2?family=Schoolbell&display=swap",
    "Scope One": "https://fonts.googleapis.com/css2?family=Scope+One&display=swap",
    "Seaweed Script": "https://fonts.googleapis.com/css2?family=Seaweed+Script&display=swap",
    "Secular One": "https://fonts.googleapis.com/css2?family=Secular+One&display=swap",
    "Sedgwick Ave": "https://fonts.googleapis.com/css2?family=Sedgwick+Ave&display=swap",
    "Sedgwick Ave Display": "https://fonts.googleapis.com/css2?family=Sedgwick+Ave+Display&display=swap",
    "Sevillana": "https://fonts.googleapis.com/css2?family=Sevillana&display=swap",
    "Seymour One": "https://fonts.googleapis.com/css2?family=Seymour+One&display=swap",
    "Shadows Into Light": "https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap",
    "Shadows Into Light Two": "https://fonts.googleapis.com/css2?family=Shadows+Into+Light+Two&display=swap",
    "Shanti": "https://fonts.googleapis.com/css2?family=Shanti&display=swap",
    "Share": "https://fonts.googleapis.com/css2?family=Share&display=swap",
    "Share Tech": "https://fonts.googleapis.com/css2?family=Share+Tech&display=swap",
    "Share Tech Mono": "https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap",
    "Shojumaru": "https://fonts.googleapis.com/css2?family=Shojumaru&display=swap",
    "Short Stack": "https://fonts.googleapis.com/css2?family=Short+Stack&display=swap",
    "Shrikhand": "https://fonts.googleapis.com/css2?family=Shrikhand&display=swap",
    "Siemreap": "https://fonts.googleapis.com/css2?family=Siemreap&display=swap",
    "Sigmar One": "https://fonts.googleapis.com/css2?family=Sigmar+One&display=swap",
    "Signika": "https://fonts.googleapis.com/css2?family=Signika&display=swap",
    "Signika Negative": "https://fonts.googleapis.com/css2?family=Signika+Negative&display=swap",
    "Simonetta": "https://fonts.googleapis.com/css2?family=Simonetta&display=swap",
    "Single Day": "https://fonts.googleapis.com/css2?family=Single+Day&display=swap",
    "Sintony": "https://fonts.googleapis.com/css2?family=Sintony&display=swap",
    "Sirin Stencil": "https://fonts.googleapis.com/css2?family=Sirin+Stencil&display=swap",
    "Six Caps": "https://fonts.googleapis.com/css2?family=Six+Caps&display=swap",
    "Skranji": "https://fonts.googleapis.com/css2?family=Skranji&display=swap",
    "Slabo 13px": "https://fonts.googleapis.com/css2?family=Slabo+13px&display=swap",
    "Slabo 27px": "https://fonts.googleapis.com/css2?family=Slabo+27px&display=swap",
    "Slackey": "https://fonts.googleapis.com/css2?family=Slackey&display=swap",
    "Smokum": "https://fonts.googleapis.com/css2?family=Smokum&display=swap",
    "Smythe": "https://fonts.googleapis.com/css2?family=Smythe&display=swap",
    "Sniglet": "https://fonts.googleapis.com/css2?family=Sniglet&display=swap",
    "Snippet": "https://fonts.googleapis.com/css2?family=Snippet&display=swap",
    "Snowburst One": "https://fonts.googleapis.com/css2?family=Snowburst+One&display=swap",
    "Sofadi One": "https://fonts.googleapis.com/css2?family=Sofadi+One&display=swap",
    "Sofia": "https://fonts.googleapis.com/css2?family=Sofia&display=swap",
    "Song Myung": "https://fonts.googleapis.com/css2?family=Song+Myung&display=swap",
    "Sonsie One": "https://fonts.googleapis.com/css2?family=Sonsie+One&display=swap",
    "Sorts Mill Goudy": "https://fonts.googleapis.com/css2?family=Sorts+Mill+Goudy&display=swap",
    "Source Code Pro": "https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap",
    "Source Sans Pro": "https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap",
    "Source Serif Pro": "https://fonts.googleapis.com/css2?family=Source+Serif+Pro&display=swap",
    "Space Mono": "https://fonts.googleapis.com/css2?family=Space+Mono&display=swap",
    "Special Elite": "https://fonts.googleapis.com/css2?family=Special+Elite&display=swap",
    "Spectral": "https://fonts.googleapis.com/css2?family=Spectral&display=swap",
    "Spectral SC": "https://fonts.googleapis.com/css2?family=Spectral+SC&display=swap",
    "Spicy Rice": "https://fonts.googleapis.com/css2?family=Spicy+Rice&display=swap",
    "Spinnaker": "https://fonts.googleapis.com/css2?family=Spinnaker&display=swap",
    "Spirax": "https://fonts.googleapis.com/css2?family=Spirax&display=swap",
    "Squada One": "https://fonts.googleapis.com/css2?family=Squada+One&display=swap",
    "Sree Krushnadevaraya": "https://fonts.googleapis.com/css2?family=Sree+Krushnadevaraya&display=swap",
    "Sriracha": "https://fonts.googleapis.com/css2?family=Sriracha&display=swap",
    "Srisakdi": "https://fonts.googleapis.com/css2?family=Srisakdi&display=swap",
    "Staatliches": "https://fonts.googleapis.com/css2?family=Staatliches&display=swap",
    "Stalemate": "https://fonts.googleapis.com/css2?family=Stalemate&display=swap",
    "Stalinist One": "https://fonts.googleapis.com/css2?family=Stalinist+One&display=swap",
    "Stardos Stencil": "https://fonts.googleapis.com/css2?family=Stardos+Stencil&display=swap",
    "Stint Ultra Condensed": "https://fonts.googleapis.com/css2?family=Stint+Ultra+Condensed&display=swap",
    "Stint Ultra Expanded": "https://fonts.googleapis.com/css2?family=Stint+Ultra+Expanded&display=swap",
    "Stoke": "https://fonts.googleapis.com/css2?family=Stoke&display=swap",
    "Strait": "https://fonts.googleapis.com/css2?family=Strait&display=swap",
    "Stylish": "https://fonts.googleapis.com/css2?family=Stylish&display=swap",
    "Sue Ellen Francisco": "https://fonts.googleapis.com/css2?family=Sue+Ellen+Francisco&display=swap",
    "Suez One": "https://fonts.googleapis.com/css2?family=Suez+One&display=swap",
    "Sumana": "https://fonts.googleapis.com/css2?family=Sumana&display=swap",
    "Sunflower": "https://fonts.googleapis.com/css2?family=Sunflower&display=swap",
    "Sunshiney": "https://fonts.googleapis.com/css2?family=Sunshiney&display=swap",
    "Supermercado One": "https://fonts.googleapis.com/css2?family=Supermercado+One&display=swap",
    "Sura": "https://fonts.googleapis.com/css2?family=Sura&display=swap",
    "Suranna": "https://fonts.googleapis.com/css2?family=Suranna&display=swap",
    "Suravaram": "https://fonts.googleapis.com/css2?family=Suravaram&display=swap",
    "Suwannaphum": "https://fonts.googleapis.com/css2?family=Suwannaphum&display=swap",
    "Swanky and Moo Moo": "https://fonts.googleapis.com/css2?family=Swanky+and+Moo+Moo&display=swap",
    "Syncopate": "https://fonts.googleapis.com/css2?family=Syncopate&display=swap",
    "Tahoma": null,
    "Tajawal": "https://fonts.googleapis.com/css2?family=Tajawal&display=swap",
    "Tangerine": "https://fonts.googleapis.com/css2?family=Tangerine&display=swap",
    "Taprom": "https://fonts.googleapis.com/css2?family=Taprom&display=swap",
    "Tauri": "https://fonts.googleapis.com/css2?family=Tauri&display=swap",
    "Taviraj": "https://fonts.googleapis.com/css2?family=Taviraj&display=swap",
    "Teko": "https://fonts.googleapis.com/css2?family=Teko&display=swap",
    "Telex": "https://fonts.googleapis.com/css2?family=Telex&display=swap",
    "Tenali Ramakrishna": "https://fonts.googleapis.com/css2?family=Tenali+Ramakrishna&display=swap",
    "Tenor Sans": "https://fonts.googleapis.com/css2?family=Tenor+Sans&display=swap",
    "Text Me One": "https://fonts.googleapis.com/css2?family=Text+Me+One&display=swap",
    "Thasadith": "https://fonts.googleapis.com/css2?family=Thasadith&display=swap",
    "The Girl Next Door": "https://fonts.googleapis.com/css2?family=The+Girl+Next+Door&display=swap",
    "Tienne": "https://fonts.googleapis.com/css2?family=Tienne&display=swap",
    "Tillana": "https://fonts.googleapis.com/css2?family=Tillana&display=swap",
    "Times New Roman": null,
    "Timmana": "https://fonts.googleapis.com/css2?family=Timmana&display=swap",
    "Tinos": "https://fonts.googleapis.com/css2?family=Tinos&display=swap",
    "Titan One": "https://fonts.googleapis.com/css2?family=Titan+One&display=swap",
    "Titillium Web": "https://fonts.googleapis.com/css2?family=Titillium+Web&display=swap",
    "Trade Winds": "https://fonts.googleapis.com/css2?family=Trade+Winds&display=swap",
    "Trebuchet MS": null,
    "Trirong": "https://fonts.googleapis.com/css2?family=Trirong&display=swap",
    "Trocchi": "https://fonts.googleapis.com/css2?family=Trocchi&display=swap",
    "Trochut": "https://fonts.googleapis.com/css2?family=Trochut&display=swap",
    "Trykker": "https://fonts.googleapis.com/css2?family=Trykker&display=swap",
    "Tulpen One": "https://fonts.googleapis.com/css2?family=Tulpen+One&display=swap",
    "Ubuntu": "https://fonts.googleapis.com/css2?family=Ubuntu&display=swap",
    "Ubuntu Condensed": "https://fonts.googleapis.com/css2?family=Ubuntu+Condensed&display=swap",
    "Ubuntu Mono": "https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap",
    "Ultra": "https://fonts.googleapis.com/css2?family=Ultra&display=swap",
    "Uncial Antiqua": "https://fonts.googleapis.com/css2?family=Uncial+Antiqua&display=swap",
    "Underdog": "https://fonts.googleapis.com/css2?family=Underdog&display=swap",
    "Unica One": "https://fonts.googleapis.com/css2?family=Unica+One&display=swap",
    "UnifrakturCook": "https://fonts.googleapis.com/css2?family=UnifrakturCook&display=swap",
    "UnifrakturMaguntia": "https://fonts.googleapis.com/css2?family=UnifrakturMaguntia&display=swap",
    "Unkempt": "https://fonts.googleapis.com/css2?family=Unkempt&display=swap",
    "Unlock": "https://fonts.googleapis.com/css2?family=Unlock&display=swap",
    "Unna": "https://fonts.googleapis.com/css2?family=Unna&display=swap",
    "VT323": "https://fonts.googleapis.com/css2?family=VT323&display=swap",
    "Vampiro One": "https://fonts.googleapis.com/css2?family=Vampiro+One&display=swap",
    "Varela": "https://fonts.googleapis.com/css2?family=Varela&display=swap",
    "Varela Round": "https://fonts.googleapis.com/css2?family=Varela+Round&display=swap",
    "Vast Shadow": "https://fonts.googleapis.com/css2?family=Vast+Shadow&display=swap",
    "Verdana": null,
    "Vesper Libre": "https://fonts.googleapis.com/css2?family=Vesper+Libre&display=swap",
    "Vibur": "https://fonts.googleapis.com/css2?family=Vibur&display=swap",
    "Vidaloka": "https://fonts.googleapis.com/css2?family=Vidaloka&display=swap",
    "Viga": "https://fonts.googleapis.com/css2?family=Viga&display=swap",
    "Voces": "https://fonts.googleapis.com/css2?family=Voces&display=swap",
    "Volkhov": "https://fonts.googleapis.com/css2?family=Volkhov&display=swap",
    "Vollkorn": "https://fonts.googleapis.com/css2?family=Vollkorn&display=swap",
    "Vollkorn SC": "https://fonts.googleapis.com/css2?family=Vollkorn+SC&display=swap",
    "Voltaire": "https://fonts.googleapis.com/css2?family=Voltaire&display=swap",
    "Waiting for the Sunrise": "https://fonts.googleapis.com/css2?family=Waiting+for+the+Sunrise&display=swap",
    "Wallpoet": "https://fonts.googleapis.com/css2?family=Wallpoet&display=swap",
    "Walter Turncoat": "https://fonts.googleapis.com/css2?family=Walter+Turncoat&display=swap",
    "Warnes": "https://fonts.googleapis.com/css2?family=Warnes&display=swap",
    "Wellfleet": "https://fonts.googleapis.com/css2?family=Wellfleet&display=swap",
    "Wendy One": "https://fonts.googleapis.com/css2?family=Wendy+One&display=swap",
    "Wire One": "https://fonts.googleapis.com/css2?family=Wire+One&display=swap",
    "Work Sans": "https://fonts.googleapis.com/css2?family=Work+Sans&display=swap",
    "Yanone Kaffeesatz": "https://fonts.googleapis.com/css2?family=Yanone+Kaffeesatz&display=swap",
    "Yantramanav": "https://fonts.googleapis.com/css2?family=Yantramanav&display=swap",
    "Yatra One": "https://fonts.googleapis.com/css2?family=Yatra+One&display=swap",
    "Yellowtail": "https://fonts.googleapis.com/css2?family=Yellowtail&display=swap",
    "Yeon Sung": "https://fonts.googleapis.com/css2?family=Yeon+Sung&display=swap",
    "Yeseva One": "https://fonts.googleapis.com/css2?family=Yeseva+One&display=swap",
    "Yesteryear": "https://fonts.googleapis.com/css2?family=Yesteryear&display=swap",
    "Yrsa": "https://fonts.googleapis.com/css2?family=Yrsa&display=swap",
    "ZCOOL KuaiLe": "https://fonts.googleapis.com/css2?family=ZCOOL+KuaiLe&display=swap",
    "ZCOOL QingKe HuangYou": "https://fonts.googleapis.com/css2?family=ZCOOL+QingKe+HuangYou&display=swap",
    "ZCOOL XiaoWei": "https://fonts.googleapis.com/css2?family=ZCOOL+XiaoWei&display=swap",
    "Zeyada": "https://fonts.googleapis.com/css2?family=Zeyada&display=swap",
    "Zhi Mang Xing": "https://fonts.googleapis.com/css2?family=Zhi+Mang+Xing&display=swap",
    "Zilla Slab": "https://fonts.googleapis.com/css2?family=Zilla+Slab&display=swap",
    "Zilla Slab Highlight": "https://fonts.googleapis.com/css2?family=Zilla+Slab&display=swap"
};